export const POKEMONS_LIST_REQUEST = "POKEMONS_LIST_REQUEST";
export const POKEMONS_LIST_SUCCESS = "POKEMONS_LIST_SUCCESS";
export const POKEMONS_LIST_FAIL = "POKEMONS_LIST_FAIL";

export const LOCATIONS_LIST_REQUEST = "LOCATIONS_LIST_REQUEST";
export const LOCATIONS_LIST_SUCCESS = "LOCATIONS_LIST_SUCCESS";
export const LOCATIONS_LIST_FAIL = "LOCATIONS_LIST_FAIL";